name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      user: actions/checkout@v2

    - name: Set up Python
      user: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    - name: Run tests
      run: |
      pytest _test.py